<?php
function get_country_name($country_code){
$countries = array
(
"AF"=>"Afghanistan",
"AL"=>"Albania",
"DZ"=>"Algeria",
"AO"=>"Angola",
"AR"=>"Argentina",
"AM"=>"Armenia",
"AU"=>"Australia",
"AT"=>"Austria",
"AZ"=>"Azerbaijan",
"BS"=>"Bahamas",
"BD"=>"Bangladesh",
"BY"=>"Belarus",
"BE"=>"Belgium",
"BZ"=>"Belize",
"BJ"=>"Benin",
"BT"=>"Bhutan",
"BO"=>"Bolivia",
"BA"=>"Bosnia and Herzegovina",
"BW"=>"Botswana",
"BR"=>"Brazil",
"BN"=>"Brunei Darussalam",
"BG"=>"Bulgaria",
"BF"=>"Burkina Faso",
"BI"=>"Burundi",
"KH"=>"Cambodia",
"CM"=>"Cameroon",
"CA"=>"Canada",
"CF"=>"Central African Republic",
"TD"=>"Chad",
"CL"=>"Chile",
"CN"=>"China",
"CO"=>"Colombia",
"CG"=>"Congo",
"CR"=>"Costa Rica",
"HR"=>"Croatia",
"CU"=>"Cuba",
"CY"=>"Cyprus",
"CZ"=>"Czech Republic",
"CD"=>"Democratic Republic of Congo",
"DK"=>"Denmark",
"DP"=>"Diamond Princess",
"DJ"=>"Djibouti",
"DO"=>"Dominican Republic",
"CD"=>"DR Congo",
"EC"=>"Ecuador",
"EG"=>"Egypt",
"SV"=>"El Salvador",
"GQ"=>"Equatorial Guinea",
"ER"=>"Eritrea",
"EE"=>"Estonia",
"ET"=>"Ethiopia",
"FK"=>"Falkland Islands",
"FJ"=>"Fiji",
"FI"=>"Finland",
"FR"=>"France",
"GF"=>"French Guiana",
"TF"=>"French Southern Territories",
"GA"=>"Gabon",
"GM"=>"Gambia",
"GE"=>"Georgia",
"DE"=>"Germany",
"GH"=>"Ghana",
"GR"=>"Greece",
"GL"=>"Greenland",
"GT"=>"Guatemala",
"GN"=>"Guinea",
"GW"=>"Guinea-Bissau",
"GY"=>"Guyana",
"HT"=>"Haiti",
"HN"=>"Honduras",
"HK"=>"Hong Kong",
"HU"=>"Hungary",
"IS"=>"Iceland",
"IN"=>"India",
"ID"=>"Indonesia",
"IR"=>"Iran",
"IQ"=>"Iraq",
"IE"=>"Ireland",
"IL"=>"Israel",
"IT"=>"Italy",
"CI"=>"Ivory Coast",
"JM"=>"Jamaica",
"JP"=>"Japan",
"JO"=>"Jordan",
"KZ"=>"Kazakhstan",
"KE"=>"Kenya",
"KP"=>"Korea",
"XK"=>"Kosovo",
"KW"=>"Kuwait",
"KG"=>"Kyrgyzstan",
"LA"=>"Lao",
"LV"=>"Latvia",
"LB"=>"Lebanon",
"LS"=>"Lesotho",
"LR"=>"Liberia",
"LY"=>"Libya",
"LT"=>"Lithuania",
"LU"=>"Luxembourg",
"MK"=>"Macedonia",
"MG"=>"Madagascar",
"MW"=>"Malawi",
"MY"=>"Malaysia",
"ML"=>"Mali",
"MR"=>"Mauritania",
"MX"=>"Mexico",
"MD"=>"Moldova",
"MN"=>"Mongolia",
"ME"=>"Montenegro",
"MA"=>"Morocco",
"MZ"=>"Mozambique",
"MM"=>"Myanmar",
"NA"=>"Namibia",
"NP"=>"Nepal",
"NL"=>"Netherlands",
"NC"=>"New Caledonia",//
"NZ"=>"New Zealand",
"NI"=>"Nicaragua",
"NE"=>"Niger",
"NG"=>"Nigeria",
"KP"=>"North Korea",
"NO"=>"Norway",
"OM"=>"Oman",
"PK"=>"Pakistan",
"PS"=>"Palestine",

"PA"=>"Panama",
"PG"=>"Papua New Guinea",
"PY"=>"Paraguay",
"PE"=>"Peru",
"PH"=>"Philippines",
"PL"=>"Poland",
"PT"=>"Portugal",
"PR"=>"Puerto Rico",
"QA"=>"Qatar",
"XK"=>"Republic of Kosovo",
"RO"=>"Romania",
"RU"=>"Russia",
"RW"=>"Rwanda",
"SA"=>"Saudi Arabia",
"SN"=>"Senegal",
"RS"=>"Serbia",
"SL"=>"Sierra Leone",
"SG"=>"Singapore",
"SK"=>"Slovakia",
"SI"=>"Slovenia",
"SB"=>"Solomon Islands",
"SO"=>"Somalia",
"ZA"=>"South Africa",
"KR"=>"South Korea",
"SS"=>"South Sudan",
"ES"=>"Spain",
"LK"=>"Sri Lanka",
"SD"=>"Sudan",
"SR"=>"Suriname",
"SJ"=>"Svalbard and Jan Mayen",
"SZ"=>"Swaziland",
"SE"=>"Sweden",
"CH"=>"Switzerland",
"SY"=>"Syrian Arab Republic",
"TW"=>"Taiwan",
"TJ"=>"Tajikistan",
"TZ"=>"Tanzania",
"TH"=>"Thailand",
"TL"=>"Timor-Leste",
"TG"=>"Togo",
"TT"=>"Trinidad and Tobago",
"TN"=>"Tunisia",
"TR"=>"Turkey",
"TM"=>"Turkmenistan",
"AE"=>"UAE",
"UG"=>"Uganda",
"UA"=>"Ukraine",
"GB"=>"United Kingdom",
"UY"=>"Uruguay",
"US"=>"USA",
"UZ"=>"Uzbekistan",
"VU"=>"Vanuatu",
"VE"=>"Venezuela",
"VN"=>"Vietnam",
"EH"=>"Western Sahara",
"YE"=>"Yemen",
"ZM"=>"Zambia",
"ZW"=>"Zimbabwe"
);
  if(isset($countries[$country_code])){
        return $c_name=$countries[$country_code];
    }else{
        return false;
    } 
}
function cvct_interchange_name($country_code){

    $countries = array
   (
    "China"=>"CN",
   "Afghanistan"=>"AF",
  
"Ghana"=>"GH",
"Greece"=>"GR",
"Greenland"=>"GL",
"Guatemala"=>"GT",
"Guinea"=>"GN",
"Guinea-Bissau"=>"GW",
"Guyana"=>"GY",
"Haiti"=>"HT",
"Honduras"=>"HN",
"Hong Kong"=>"HK",
"Hungary"=>"HU",
"Iceland"=>"IS",
"India"=>"IN",
"Indonesia"=>"ID",
"Iran"=>"IR",
"Iraq"=>"IQ",
"Ireland"=>"IE",
"Israel"=>"IL",
"Italy"=>"IT",
"Ivory Coast"=>"CI",
"Jamaica"=>"JM",
"Japan"=>"JP",
"Jordan"=>"JO",
"Kazakhstan"=>"KZ",
"Kenya"=>"KE",
"Korea"=>"KP",
"Kosovo"=>"XK",
"Kuwait"=>"KW",
"Kyrgyzstan"=>"KG",
"Lao"=>"LA",
"Latvia"=>"LV",
"Lebanon"=>"LB",
"Lesotho"=>"LS",
"Liberia"=>"LR",
"Libya"=>"LY",
"Lithuania"=>"LT",
"Luxembourg"=>"LU",
"North Macedonia"=>"MK",
"Madagascar"=>"MG",
"Malawi"=>"MW",
"Malaysia"=>"MY",
"Mali"=>"ML",
"Mauritania"=>"MR",
"Mexico"=>"MX",
"Moldova"=>"MD",
"Mongolia"=>"MN",
"Montenegro"=>"ME",
"Morocco"=>"MA",
"Mozambique"=>"MZ",
"Myanmar"=>"MM",
"Namibia"=>"NA",
"Nepal"=>"NP",
"Netherlands"=>"NL",
   "New Caledonia"=>"NC",//
"New Zealand"=>"NZ",
"Nicaragua"=>"NI",
"Niger"=>"NE",
"Nigeria"=>"NG",
"North Korea"=>"KP",
"Norway"=>"NO",
"Oman"=>"OM",
"Pakistan"=>"PK",
"Palestine"=>"PS",

"Panama"=>"PA",
"Papua New Guinea"=>"PG",
"Paraguay"=>"PY",
"Peru"=>"PE",
"Philippines"=>"PH",
"Poland"=>"PL",
"Portugal"=>"PT",
"Puerto Rico"=>"PR",
"Qatar"=>"QA",
"Republic of Kosovo"=>"XK",
"Romania"=>"RO",
"Russia"=>"RU",
"Rwanda"=>"RW",
"Saudi Arabia"=>"SA",
"Senegal"=>"SN",
"Serbia"=>"RS",
"Sierra Leone"=>"SL",
"Singapore"=>"SG",
"Slovakia"=>"SK",
"Slovenia"=>"SI",
"Solomon Islands"=>"SB",
"Somalia"=>"SO",
"South Africa"=>"ZA",
"S. Korea"=>"KR",
"South Sudan"=>"SS",
"Spain"=>"ES",
"Sri Lanka"=>"LK",
"Sudan"=>"SD",
"Suriname"=>"SR",
"Svalbard and Jan Mayen"=>"SJ",
//"Swaziland"=>"SZ",
"Sweden"=>"SE",
"Switzerland"=>"CH",
"Syria"=>"SY",
"Taiwan"=>"TW",
"Tajikistan"=>"TJ",
"Tanzania"=>"TZ",
"Thailand"=>"TH",
"Timor-Leste"=>"TL",
"Togo"=>"TG",
"Trinidad and Tobago"=>"TT",
"Tunisia"=>"TN",
"Turkey"=>"TR",
"Turkmenistan"=>"TM",
"UAE"=>"AE",
"Uganda"=>"UG",
"Ukraine"=>"UA",
"United Kingdom"=>"GB",
"Uruguay"=>"UY",
"USA"=>"US",
"Uzbekistan"=>"UZ",
"Vanuatu"=>"VU",
"Venezuela"=>"VE",
"Vietnam"=>"VN",
"UK"=>"GB",

"Western Sahara"=>"EH",
"Yemen"=>"YE",
"Zambia"=>"ZM",
"Zimbabwe"=>"ZW",
'Albania' => 'AL', 'Algeria' => 'DZ', 'Angola' => 'AO', 'Argentina' => 'AR', 
'Armenia' => 'AM', 'Australia' => 'AU', 'Austria' => 'AT', 'Azerbaijan' => 'AZ', 
'Bahamas' => 'BS', 'Bangladesh' => 'BD', 'Belarus' => 'BY', 'Belgium' => 'BE', 'Belize' => 'BZ', 
'Benin' => 'BJ', 'Bhutan' => 'BT', 'Bolivia' => 'BO', 'Bosnia and Herzegovina' => 'BA', 'Botswana' => 'BW', 
'Brazil' => 'BR', 'Brunei Darussalam' => 'BN', 'Bulgaria' => 'BG', 'Burkina Faso' => 'BF', 'Burundi' => 'BI', 
'Cambodia' => 'KH', 'Cameroon' => 'CM', 'Canada' => 'CA', 'CAR' => 'CF', 'Chad' => 'TD',
 'Chile' => 'CL', 'China' => 'CN', 'Colombia' => 'CO', 'Congo' => 'CG', 'Costa Rica' => 'CR', 'Croatia' => 'HR', 
 'Cuba' => 'CU', 'Cyprus' => 'CY', 'Czechia' => 'CZ', 'DR Congo' => 'CD', 'Denmark' => 'DK', 'Diamond Princess' => 'DP', 
 'Djibouti' => 'DJ', 'Dominican Republic' => 'DO', 'Ecuador' => 'EC', 'Egypt' => 'EG', 'El Salvador' => 'SV', 
 'Equatorial Guinea' => 'GQ', 'Eritrea' => 'ER', 'Estonia' => 'EE', 'Ethiopia' => 'ET', 'Falkland Islands' => 'FK',
  'Fiji' => 'FJ', 'Finland' => 'FI', 'France' => 'FR', 'French Guiana' => 'GF', 'French Southern Territories' => 'TF',
 'Gabon' => 'GA', 'Gambia' => 'GM', 'Georgia' => 'GE', 'Germany' => 'DE',
 'Bahrain' => 'BH','San Marino'=>'SM', 'Andorra' => 'AD', 'Malta' => 'MT', 'Brunei' => 'BN', 'Réunion' => 'RE', 
 'Liechtenstein' => 'LI', 'Mauritius' => 'MU', 'Mayotte' => 'YT', 'Guam' => 'GU', 'Monaco'=>'MC', 'French Polynesia'=>'PF',
 'Barbados' => 'BB', 'U.S. Virgin Islands' => 'VI', 'Gibraltar' => 'GI', 'Isle of Man' => 'IM', 'Maldives' => 'MV', 
 'Aruba'=> 'AW', 
 'Saint Martin' => 'MF',
 'Seychelles' => 'SC',
 'Bermuda' => 'BM',
 'Cayman Islands' => 'KY',
 'Curaçao' => 'CW',
 'Antigua and Barbuda' => 'AG',
 'Saint Lucia' => 'LC',
 'Dominica' => 'DM',
 'Laos' => 'LA',
 'Sint Maarten' => 'SX',
 'Grenada' => 'GD',
 'Montserrat' => 'MS',
 'Turks and Caicos' => 'TC',
 'Guadeloupe' => 'GP',
 'Martinique' => 'MQ',
 'Macao' => 'MO',
 'Eswatini' => 'SZ',
 'Cabo Verde' => 'CV',
 'St. Barth' => 'BL',
 'Cabo Verde' => 'CV',
 'Vatican City' => 'VA',
 'St. Vincent Grenadines' => 'VC',
 'DRC' => 'CD'

   );
   if(isset($countries[$country_code])){
      return $c_name = $countries[$country_code];
   }
}


